### PR TITLE
Feature/guest command

### PR DESCRIPTION
**Pull request by mdarrik**
Adds a command so you can run !guest and drop your guest's name and social media links in chat. May eventually want to expand it to include things like a description or a link to their product/personal site.

### CODE REVIEW

**Comment by mdarrik** [comment]
Realized it may just be easier to let you set the whole guest message. If I get a chance I'll make the change after work today. The current method only lets you to address your guests by their first name

**Comment by jlengstorf** [comment]
I feel like it would be ideal if this was settable via the chat so we don't need a PR per episode. Or... actually, maybe I can pull it from the .txt files I use for OBS.

I'm thinking this will probably end up needing some kind of database. Maybe I'll get someone from e.g. Prisma/Fauna/Hasura to come on and teach me how to back my chatbot with a DB. 😂

**Comment by mdarrik** [comment]
This should be settable from chat. The guest variable should live as long
as the bot is active.

**Comment by jlengstorf** [comment]
Oh, interesting. I hadn’t really considered that we could just use variable state. 🤔

**Comment by mdarrik** [comment]
Yeah, I only realized I could do this because I'm doing something similar
for ID's in a vue app. In the future though you could probably use your
schedule or something to auto populate the guest command. I just wanted to
get you one to start. Though I think there's a better, simpler solution
where it doesn't split the message. Then you could just write up the
message in a text file and paste it in.

Instead of a full fauna db you could also just use node-storage

**Comment by jlengstorf** [comment]
Hey! This one is now possible using the custom stuff we built on stream today with Fauna. I'm going to close, but thanks so much for getting this started!

**Pull request closed without merging**
